### PR TITLE
multilingual pyaxis

### PR DESCRIPTION
**Pull request by vancauwe**
- new functions to handle multiple languages
- unit tests for these functions
- small code refactoring 

Of important note : The metadata of the PX files is somewhat tricky when multiple languages are involved because some fields are just `HEADING[de]/[fr]/[it]` but some fields have language information in their name, i.e. `VALUES(Jahr)` which becomes `VALUES[fr](Années)`. Is it unclear to what extent this is recurrent across PX formats, so the code needs to take into account these aspects and remain generic.

### CODE REVIEW

**Review by sabinem — CHANGES_REQUESTED** [review]
My review is that I approve the code, but challenge the approach, that was taken in this PR: 

I really like you code, it is well structured, easy to read and just fine. But I want to raise a more general question: Are we on the right track with the approach to translations that this PR proposes.

**Challenging the approach towards translations taken by this PR:**
To me the question is what should translations of a px cubes be.

In this PR the output of `px['TRANSLATION']` stays very much within the px format. It offers a dictionary, that repeats px elements in different languages. 

**Px files have a lot or redundancy build in**

That is exactly one feature in the px format, that things are repeated many times over, even though they should be there only once. 

We have that with dimensions, that are redefined in every px file, even though they are probably the same over many px files, such as for example the cantons of Switzerland. 

And we have that with translations within the px files as well.

**Translations in px file are string translations, stored in a redundant way** 

What px files use is string translations, but they are not stored as string translations and can only be interpreted in the px context. 

So take for example a dimension such as the STUB in the example data that has been added for the multilingual px files: 

``` 
STUB="Wirtschaftsabteilung","Ausbildungsniveau","Schwierigkeiten","Gewichtung";
STUB[fr]="Division �conomique","Niveau de formation","Niveau de difficult�s","Pond�ration";
STUB[it]="Divisione economica","Livello di formazione","Difficolt� di reclutamento","Ponderazione";
STUB[en]="Economic division","Education level","Difficulties","Weight";
``` 

The translation of `Ausbildungsniveau` in French is `Niveau de formation`. 
This translation is then used again in `VALUES[fr]("Niveau de formation")`. 
But the way that is stored as above: the translation can only be understood by knowing the px format. 

An alternative approach would be to store the translations in json files such as 

```fr.json
{
  "Ausbildungsniveau": "Niveau de formation",
}
``` 

The data and metadata could then be stored once in the original language, but offer locale, by using the translation files to bring back whatever locale is requested.

**Test whether translation is needed, when using string translations**

With this approach I would also test the px values when analysing the metadata and only translate when values indeed differ: 

For example the translation of `CODES` often does not make sense:

```
CODES("Ausbildungsniveau")="1","2","3","4";
CODES[fr]("Niveau de formation")="1","2","3","4";
```

**When moving towards semantic data: it is string translation that is needed**

Since we want to move with the translations towards semantic metadata and away from px file format, the string translation approach for translations would make more sense to me: 

Later in `turtle` it would look like this: 

```
<px-x-0602000000_107/cube/observation/20190103T120000055Z> a cube:Observation ;
  dh:ausbilungsniveau <ausbildungsniveau/#berufslehre> .
```

```
<ausbildungsniveau/#berufslehre> a skos:Concept ;
  skos:prefLabel "Berufslehre"@de ,
     "Apprentissage"@fr .
```

So the point here is that in `rdf` it would also be string translations. Then my suggestion would be to move toward string translations already with this PR.

**Comment by arc17854** [comment]
Thank you for your contributions. I really like the code in the pull request (PR).

To ensure I understand the questions correctly, I will provide my point of view.

Regarding Laure's question, when VALUE does not specify a language, it is assumed to be the default language. For example, please see: https://www.eustat.eus/bankupx/Resources/PX/Databases/DB/PX_010151_cel_cel01.px

As for Sabiene's proposal, this PR enables pyaxis to return a translated DataFrame, which is an easy-to-use and easy-to-understand feature.

When discussing the best way to achieve portability to other formats such as RDF, are you suggesting that the package should return both a DataFrame and a dictionary with the translations?

**Comment by sabinem** [comment]
@arc17854 Thanks for also sharing your viewpoint. 

You wrote: 

> When discussing the best way to achieve portability to other formats such as RDF, are you suggesting that the package should return both a DataFrame and a dictionary with the translations?

The thing is that in this PR the output is already offering a dictionary of translations and it is exactly this dictionary that I want to discuss here. See the `README`:  the PR adds `px['TRANSLATION']` to the output: 

```
px['DATA']
px['METADATA']
px['TRANSLATION']
```

And the discussion is about whether the way the `px['TRANSLATION']` that are returned is what we intend to offer.

**Translations**

The PR includes another new feature, that manifests itself as `px['TRANSLATION']`. Here I would suggest to have string translations from the default language instead of a dictionary of px fields: 

Currently we get: 

```
STUB {'de': ['Jahr', 'Kanton'], 'fr': ['Année', 'Canton'], 'it': ['Anno', 'Cantone'], 'en': ['Year', 'Canton']}
HEADING {'de': ['Geschlecht des Kindes', 'Altersklasse des Kindes'], 'fr': ["Sexe de l'enfant", "Classe d'âge de l'enfant"], 'it': ['Sesso del bambino', 'Etŕ del bambino'], 'en': ['Sex of child', 'Age of child']}
```

This translates within the px file format. But what we want to get in RDF is the actual data with metadata and translations. 

So the metadata here are the dimensions `Jahr` with translations `en`: `Year`, `fr`: `Année`, etc. This is one dimension.
Then there is another dimension: `Kanton` with translations `en`: `Canton`, etc.

Later in RDF these two dimensions would not be together in one list, but they will be in separate places. So why don't move to these string translations now already?

Such as `en.json`: `{"Jahr": "year", "Kanton": "Canton"}`
`fr.json`: `{"Jahr": "Année", "Kanton": "Canton"}` 

Then whenever `Kanton` appears in the `px['METADATA']`: you can go and check if there is a string translation for that string or not: then instead of storing all these dictionaries you would just store all the string translations and localize from there. 

**Why do I discuss this now instead of just going along with the proposed solutions?**

When we start giving translations as above in `px['TRANSLATION']`, then users of `pyaxis` will get used to this format and further build on it. 

For the translated dataframe `px['DATA']` this is fine, since there it is very clear what we offer as an output. 

But with the translations this is less forward and less clear. That is why think we need to discuss this before moving forward. 

Hope that answers your questions.

An alternative would be to not offer the translations on the interface and just use them internally. Then it would matter much less in my opinion which structure they have.

**Comment by arc17854** [comment]
Thank you, @sabinem. I think I now understand the approach.

I haven't worked with RDF files too much, but in my opinion, if the pcaxis package could provide a more user-friendly translation to the RDF format, then this pull request would be a great opportunity.

My question now is whether we're discussing the possibility of adding the option to write JSON files to disk by specifying the file path as an optional parameter, instead of storing it in `px['TRANSLATION']['fr']` which contains `{"Jahr": "Année", "Kanton": "Canton"}`, `['TRANSLATION']['en']` which contains `{"Jahr": "year", "Kanton": "Canton"}`, etc. This question arose because we referred to 'en.json' and 'fr.json'.

Regardless, I agree with both suggestions.

By the way @vancauwe, I noticed an error in the file located at https://www.eustat.eus/bankupx/Resources/PX/Databases/DB/PX_010151_cel_cel01.px.

The error is in the code block:

```
CHARSET="ANSI";
AXIS-VERSION="2005";
LANGUAGE="es";
LANGUAGES = "es","eu","en";
```


There is an extra whitespace after the `LANGUAGES` keyword. To resolve this issue, I added the following code to the `metadata_split_to_dict` function:

...
```
    for element in metadata_elements:
        name, values = split_ignore_quotation_marks(element, '=', final=False)

        # TODO avoid unexpected trailing blanks
        name = name.strip()

        name = name.replace('"', '')
        # remove leading and trailing blanks from element names
        name = name.replace('( ', '(')
        name = name.replace(' )', ')')
```
...

**Comment by vancauwe** [comment]
Thank you both for your input and review. I was also pondering how to structure this translation dictionary and I feel like we could move towards an RDF compatible format from the start. I will surely change around a few things to do so and then invite you to review again.
I am very happy to see us discussing these changes and their implementation together !

**Comment by vancauwe** [comment]
I believe @lla11358 took care of the merge conflict. I think the pull request is awaiting your approvals and then it is ready to go :)

**Review by lla11358 — APPROVED** [review]

**Pull request merged**
